# Generated by Django 4.1.3 on 2022-12-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdb_block', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField(unique=True)),
                ('unit_number', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raspberry_id', models.CharField(max_length=200, unique=True)),
                ('room_name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_webapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='SmokeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_value', models.IntegerField()),
                ('captured_date', models.DateTimeField(auto_now_add=True)),
                ('module_stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_webapp.modulestand')),
            ],
        ),
    ]
