# Generated by Django 4.1.3 on 2022-12-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
