# Generated by Django 4.1.3 on 2022-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry_location',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
