# Generated by Django 4.1.3 on 2022-12-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Household',
        ),
        migrations.RenameField(
            model_name='modulestand',
            old_name='location',
            new_name='household',
        ),
    ]
