# Generated by Django 4.1.3 on 2022-12-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0002_alter_raspberry_location_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry_location',
            name='flat_type',
            field=models.CharField(default='4-room', max_length=6),
            preserve_default=False,
        ),
    ]
