# Generated by Django 4.1.3 on 2022-12-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0002_rename_house_block_household_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulestand',
            name='captured_date',
        ),
        migrations.RemoveField(
            model_name='modulestand',
            name='smoke_value',
        ),
        migrations.CreateModel(
            name='SmokeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_value', models.IntegerField()),
                ('captured_date', models.DateTimeField(auto_now_add=True)),
                ('module_stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_webapp.modulestand')),
            ],
        ),
    ]
