# Generated by Django 4.1.3 on 2022-12-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0003_raspberry_location_flat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry',
            name='serial_id',
        ),
    ]
