# Generated by Django 4.1.3 on 2022-12-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0003_remove_modulestand_captured_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmokeValue',
            new_name='SmokeReading',
        ),
    ]
