# Generated by Django 4.1.3 on 2022-12-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0004_remove_raspberry_serial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokereading',
            name='smoke_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
