# Generated by Django 4.1.3 on 2022-12-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0006_raspberry_location_street_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry_location',
            name='postal_code',
        ),
    ]
