# Generated by Django 4.1.3 on 2022-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0007_remove_raspberry_location_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='serial_id',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
