# Generated by Django 4.1.3 on 2022-12-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0009_alter_raspberry_serial_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry',
            name='serial_id',
        ),
    ]
