# Generated by Django 4.1.3 on 2022-12-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0011_raspberry_serial_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry_location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='raspberry_location',
            name='flat_type',
        ),
        migrations.RemoveField(
            model_name='raspberry_location',
            name='street_name',
        ),
    ]
