# Generated by Django 4.1.3 on 2022-12-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0012_remove_raspberry_location_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(max_length=6)),
                ('area', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='raspberry_location',
            name='flat_info',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard_webapp.flat_info'),
            preserve_default=False,
        ),
    ]
