# Generated by Django 4.1.3 on 2022-12-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0013_flat_info_raspberry_location_flat_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry_location',
            name='flat_info',
        ),
    ]
