# Generated by Django 4.1.3 on 2022-12-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0015_raspberry_location_flat_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspberry_location',
            old_name='flat_info',
            new_name='flat_info_id',
        ),
    ]
