# Generated by Django 4.1.3 on 2022-12-27 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0016_rename_flat_info_raspberry_location_flat_info_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry_location',
            name='flat_info_id',
        ),
        migrations.AddField(
            model_name='raspberry_location',
            name='flat_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard_webapp.flat_info'),
            preserve_default=False,
        ),
    ]
