# Generated by Django 4.1.3 on 2022-12-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0018_rename_serial_id_raspberry_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry_location',
            name='flat_info',
        ),
    ]
