# Generated by Django 4.1.3 on 2022-12-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0019_remove_raspberry_location_flat_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry_location',
            name='area',
            field=models.CharField(default='Sengkang', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raspberry_location',
            name='flat_type',
            field=models.CharField(default='4-room', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raspberry_location',
            name='street_name',
            field=models.CharField(default='Fernvale Link', max_length=200),
            preserve_default=False,
        ),
    ]
