# Generated by Django 4.1.3 on 2022-12-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0020_raspberry_location_area_raspberry_location_flat_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgbcaptures',
            name='image_link',
        ),
    ]
