# Generated by Django 4.1.3 on 2022-12-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0021_remove_rgbcaptures_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermalcaptures',
            name='image_link',
        ),
    ]
