# Generated by Django 4.1.3 on 2022-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0022_remove_thermalcaptures_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgbcaptures',
            name='image',
            field=models.BinaryField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalcaptures',
            name='image',
            field=models.BinaryField(default='1'),
            preserve_default=False,
        ),
    ]
