# Generated by Django 4.1.3 on 2023-01-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0023_rgbcaptures_image_thermalcaptures_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspberry',
            old_name='serial_no',
            new_name='mac_address',
        ),
    ]
