# Generated by Django 4.1.3 on 2023-01-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0024_rename_serial_no_raspberry_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='smokereading',
            name='ch2o',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smokereading',
            name='co',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smokereading',
            name='hcn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smokereading',
            name='nh3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smokereading',
            name='voc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
