# Generated by Django 4.1.3 on 2023-01-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0025_smokereading_ch2o_smokereading_co_smokereading_hcn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.IntegerField()),
                ('nh3', models.IntegerField()),
                ('ch2o', models.IntegerField()),
                ('hcn', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_webapp.raspberry')),
            ],
        ),
    ]
