# Generated by Django 4.1.3 on 2023-01-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0026_sensor_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberry',
            name='rgb_cam_id',
        ),
        migrations.RemoveField(
            model_name='raspberry',
            name='smoke_sensor_id',
        ),
        migrations.RemoveField(
            model_name='raspberry',
            name='thermal_cam_id',
        ),
    ]
