# Generated by Django 4.1.3 on 2023-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0027_remove_raspberry_rgb_cam_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='mac_address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
