# Generated by Django 4.1.3 on 2023-02-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_webapp', '0028_alter_raspberry_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smokereading',
            name='smoke_value',
        ),
    ]
