"""
Django settings for django_dashboard project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b4hz@30#l%x$$0)-sqc!qg4d+mou(6&tr#v6)9!(s7ip%v*8y+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed hosts
# But In production make sure you include your full URL in the allowed host (for example, .allowed-domain.com) 
# or a full origin, in the format scheme://domain[:port] (for example, http://allowed-domain.com:80). 
# Port is optional, but recommended
ALLOWED_HOSTS = [
    '127.0.0.1:8000', '127.0.0.1',
    'ws://127.0.0.1:8000', 'ws://127.0.0.1',
    'ws://localhost:8000',
]

# Application definition
INSTALLED_APPS = [
    'daphne',
    'dashboard_webapp',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


#CELERY_BROKER_URL = 'redis://:p37c68b42f5775d6f62da80f0485b564b750f78a59d1497e0a829d1c554a16d16@ec2-3-230-185-236.compute-1.amazonaws.com:26980'

WSGI_APPLICATION = 'django_dashboard.wsgi.application'

# Daphne
ASGI_APPLICATION = "django_dashboard.asgi.application"

# Channels
"""
CHANNEL_LAYERS = { # for testing/local-development purposes
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}
"""
# For production + run redis server as docker image @ port 6379
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dashboard_webapp',
        'USER': 'root',
        'PASSWORD': '!password',
        'HOST': 'localhost', # 127.0.0.1
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
